on:
  workflow_dispatch:
  workflow_call:
name: Release tagged build

permissions:
  contents: write

jobs:
  release-tags:
    uses: GTNewHorizons/GTNH-Actions-Workflows/.github/workflows/release-tags.yml@master
    secrets: inherit
